version: '2'

services:
    nginx:
        image: sharaths/magento-alpine:nginx
        restart: always
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:magento.local.com
            - traefik.port=80
            - traefik.docker.network=web
        volumes:
            - ./public_html:/var/www/html:rw 
        command: >
            sh /usr/local/bin/startup.sh
        links:
           - php-fpm
        environment:
            - VERBOSE=true
            - MAGENTO_VERSION=2
        networks:
            - web    
            - network-back

    php-fpm:
        image: sharaths/magento-alpine:php-fpm-7.1
        restart: always
        volumes:
            - ./public_html:/var/www/html:rw
        networks:
            - network-back
        environment:
            - VERBOSE=true
        links:
            - mysql
            - redis
   
    mysql:
        image: sharaths/magento-alpine:mysql
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        environment:
            - VERBOSE=false
            - MYSQL_ROOT_PASSWORD=magento
            - MYSQL_USER_NAME=magento
            - MYSQL_USER_PASSWORD=magento
            - MYSQL_DATABASE=magento
        networks:
            - network-back

    redis:
        image: sharaths/magento-alpine:redis
        restart: unless-stopped
        networks:
            - network-back
        environment:
            - VERBOSE=false

networks:
   web:
     external: true
   network-back:
     external: false
